# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
- task: mirror-git-repository-vsts-task@1
- task: mirror-git-repository-vsts-task@1
  inputs:
    sourceGitRepositoryUri: 'https://dev.azure.com/BudgetBusters/FundTrackr/_git/test'
    sourceGitRepositoryPersonalAccessToken: 'xlnje4exorlfsqdlrh5xczjckqskbo6yl7lsxelo7bwo3sxjysaa'
    destinationGitRepositoryUri: 'https://github.com/alexxtsi/test.git'
    destinationGitRepositoryPersonalAccessToken: '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'

